name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  confirm_dialog: ^1.0.3
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.0
  path: ^1.8.3
  another_flushbar: ^1.12.30
  flutter_slidable: ^3.1.1
  flutter_local_notifications: ^17.2.2
  rxdart: ^0.28.0
  flutter_timezone: ^3.0.1
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - lib/assets/icon/push-pin.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/to-do-list.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/fg_to-do-list.png"
  
